export const NEIGHBOURHOOD_CLEANSED: string[] = [
  'Batignolles-Monceau',
  'Bourse',
  'Buttes-Chaumont',
  'Buttes-Montmartre',
  'Entrepôt',
  'Gobelins',
  'Hôtel-de-Ville',
  'Louvre',
  'Luxembourg',
  'Ménilmontant',
  'Observatoire',
  'Opéra',
  'Palais-Bourbon',
  'Panthéon',
  'Passy',
  'Popincourt',
  'Reuilly',
  'Temple',
  'Vaugirard',
  'Élysée',
];

export const PROPERTY_TYPE: string[] = [
  'Aparthotel',
  'Apartment',
  'Barn',
  'Bed and breakfast',
  'Boat',
  'Boutique hotel',
  'Bungalow',
  'Cabin',
  'Casa particular (Cuba)',
  'Castle',
  'Cave',
  'Chalet',
  'Condominium',
  'Cottage',
  'Dome house',
  'Earth house',
  'Guest suite',
  'Guesthouse',
  'Hostel',
  'Hotel',
  'House',
  'Houseboat',
  'Igloo',
  'Loft',
  'Nature lodge',
  'Resort',
  'Serviced apartment',
  'Tiny house',
  'Tipi',
  'Townhouse',
  'Treehouse',
  'Villa', 
];

export const ROOM_TYPE: string[] = [
  'Entire home/apt',
 'Private room',
 'Shared room',
];

export const BED_TYPE: string[] = [
  'Airbed',
 'Couch',
 'Futon',
 'Pull-out Sofa',
 'Real Bed',
];

export const AMENITIES: string[] = [
  ' toilet',
 '24-hour check-in',
 'Accessible-height bed',
 'Accessible-height toilet',
 'Air conditioning',
 'Air purifier',
 'Amazon Echo',
 'BBQ grill',
 'Baby bath',
 'Baby monitor',
 'Babysitter recommendations',
 'Balcony',
 'Bath towel',
 'Bathroom essentials',
 'Bathtub',
 'Bathtub with bath chair',
 'Beach essentials',
 'Beach view',
 'Beachfront',
 'Bed linens',
 'Bedroom comforts',
 'Bidet',
 'Body soap',
 'Breakfast',
 'Breakfast table',
 'Building staff',
 'Buzzer/wireless intercom',
 'Cable TV',
 'Carbon monoxide detector',
 'Cat(s)',
 'Ceiling fan',
 'Ceiling hoist',
 'Changing table',
 'Children’s books and toys',
 'Children’s dinnerware',
 'Cleaning before checkout',
 'Coffee maker',
 'Convection oven',
 'Cooking basics',
 'Crib',
 'DVD player',
 'Day bed',
 'Disabled parking spot',
 'Dishes and silverware',
 'Dishwasher',
 'Dog(s)',
 'Doorman',
 'Double oven',
 'Dryer',
 'EV charger',
 'Electric profiling bed',
 'Elevator',
 'En suite bathroom',
 'Espresso machine',
 'Essentials',
 'Ethernet connection',
 'Extra pillows and blankets',
 'Family/kid friendly',
 'Fire extinguisher',
 'Fireplace guards',
 'Firm mattress',
 'First aid kit',
 'Fixed grab bars for shower',
 'Fixed grab bars for toilet',
 'Flat path to front door',
 'Formal dining area',
 'Free parking on premises',
 'Free street parking',
 'Full kitchen',
 'Game console',
 'Garden or backyard',
 'Ground floor access',
 'Gym',
 'Hair dryer',
 'Handheld shower head',
 'Hangers',
 'Heated towel rack',
 'Heating',
 'High chair',
 'High-resolution computer monitor',
 'Host greets you',
 'Hot tub',
 'Hot water',
 'Hot water kettle',
 'Indoor fireplace',
 'Internet',
 'Iron',
 'Ironing Board',
 'Jetted tub',
 'Keypad',
 'Kitchen',
 'Kitchenette',
 'Lake access',
 'Laptop friendly workspace',
 'Lock on bedroom door',
 'Lockbox',
 'Long term stays allowed',
 'Luggage dropoff allowed',
 'Memory foam mattress',
 'Microwave',
 'Mini fridge',
 'Mobile hoist',
 'Mudroom',
 'Murphy bed',
 'Netflix',
 'Other pet(s)',
 'Outdoor seating',
 'Outlet covers',
 'Oven',
 'Pack ’n Play/travel crib',
 'Paid parking off premises',
 'Paid parking on premises',
 'Patio or balcony',
 'Pets allowed',
 'Pets live on this property',
 'Pillow-top mattress',
 'Pocket wifi',
 'Pool',
 'Pool with pool hoist',
 'Printer',
 'Private entrance',
 'Private living room',
 'Projector and screen',
 'Rain shower',
 'Refrigerator',
 'Roll-in shower',
 'Roll-in shower with chair',
 'Room-darkening shades',
 'Safety card',
 'Self check-in',
 'Shampoo',
 'Shower chair',
 'Single level home',
 'Ski-in/Ski-out',
 'Smart TV',
 'Smart lock',
 'Smoke detector',
 'Smoking allowed',
 'Soaking tub',
 'Sound system',
 'Stair gates',
 'Stand alone shower',
 'Stand alone steam shower',
 'Standing valet',
 'Steam oven',
 'Step-free access',
 'Stove',
 'Suitable for events',
 'Sun loungers',
 'TV',
 'Table corner guards',
 'Tennis court',
 'Terrace',
 'Toilet paper',
 'Walk-in shower',
 'Warming drawer',
 'Washer',
 'Washer / Dryer',
 'Waterfront',
 'Well-lit path to entrance',
 'Wheelchair accessible',
 'Wide clearance to bed',
 'Wide clearance to shower',
 'Wide doorway',
 'Wide entryway',
 'Wide hallway clearance',
 'Wifi',
 'Window guards',
 'Wine cooler'
];